### PR TITLE
Add the ability to export data to CSV

### PR DESCRIPTION
**Pull request by zoeesilcock**
screenshot2

### CODE REVIEW

**Comment by DarrenTsung** [comment]
Thanks for the contribution! This looks pretty good to me, I would suggest to remove the extra spaces in the CSV file as spaces could be handled as valid data in a bare-bones CSV parser (split on `,` only).

For example:
```
date, compile_time, had_errors
"05/10/2018 08:28:51", 2664, False
```

Would become:
```
date,compile_time,had_errors
"05/10/2018 08:28:51",2664,False
```

Would this work for your use case? This way it's also possible to remove the quotes from the date (as there are no commas in the data), although I'm not opposed to keeping the quotes.

Also, can I ask what you're using this CSV export functionality for? I'm assuming it'd be useful for collecting data and tracking it long term, but I don't see a way to automate this as it is.

**Comment by zoeesilcock** [comment]
That sounds like fair input, I'll definitely remove the extra spaces. I needed the quotes for the data to import into Google Sheets properly, but that might have been because of the spaces. I'll try removing the quotes also. I'll push another commit once I've had time to look at it.

I'm using this to move the data into a spreadsheet as I mentioned above. My goal is mainly to track how much time I spend waiting for compiling to complete over time. Two days is not a big enough data set for my needs.

**Comment by zoeesilcock** [comment]
I tried removing both the spaces and the quotes and it works as you said. I amended my commit and pushed it so this should be ready to merge now.

**Review by DarrenTsung — APPROVED** [review]

**Comment by DarrenTsung** [comment]
Great, glad it worked! Thanks for the PR :)

**Pull request merged**
